### ISSUE TITLE
Wrap all external libs in namespace (was Consider wrapping rapidjson in a container namespace)

### ISSUE THREAD

**Issue by sunbing81** [USCiLab/cereal#121]
Because both cereal and rapidjson are header-only and cereal contains a copy of a particular version of rapidjson, it will be conflicted if a project includes them both, unless the versions of rapidjson happen to be the same.

**Comment by c42f** [comment]
+1 for this - I have a project containing both rapidxml and rapidjson as existing dependencies.

What is the preferred implementation? One option would be to go through rapidjson and wrap all occurrences of `namespace rapidjson` with

```C++
RAPIDJSON_WRAP_NAMESPACE_ENTER
namespace rapidjson {

// ...

} // namespace rapidjson
RAPIDJSON_WRAP_NAMESPACE_EXIT
```

In `rapidjson.h`:

```C++
#ifdef RAPIDJSON_WRAPPER_NAMESPACE
#   define RAPIDJSON_WRAP_NAMESPACE_ENTER namespace RAPIDJSON_WRAPPER_NAMESPACE {
#   define RAPIDJSON_WRAP_NAMESPACE_EXIT }
#else
#   define RAPIDJSON_WRAP_NAMESPACE_ENTER
#   define RAPIDJSON_WRAP_NAMESPACE_EXIT
#endif
```

This is potentially something that could be submitted to rapidjson upstream rather than being a cereal-specific hack.  Usage in cereal as follows:

```C++
#define RAPIDJSON_WRAPPER_NAMESPACE cereal
#include <cereal/external/rapidjson/prettywriter.h>
#include <cereal/external/rapidjson/genericstream.h>
// ...
#undef RAPIDJSON_WRAPPER_NAMESPACE
```

**Comment by AzothAmmo** [comment]
Until we upgrade rapidjson/xml to newer versions I'm implementing a quick fix to this by shoving `CEREAL_` on the preprocessor stuff and throwing everything else in the cereal namespace.
