### ISSUE TITLE
Add a 'getNodeName' API to JSON/XML InputArchives

### ISSUE THREAD

**Issue by AzothAmmo** [USCiLab/cereal#166]
Thought this had happened a long time ago (see #66), got lost along the way somehow.  Will push this change to master.

**Comment by mattyclarkson** [comment]
@jhol, found the lost `getNodeName`.

**Comment by jhol** [comment]
@AzothAmmo would you be interested in making a point release with mine and @mattyclarkson 's fixes (and any others)? It would help us a lot, rather than having to wait 10 months as in the v1.0.0 - v1.1.0 release cycle. I wouldn't think it would be a bad thing for the project to release-early-release-often.

**Comment by AzothAmmo** [comment]
That's probably a good idea.  We could still have the big milestones and do something like release all (non breaking) changes up to date as a x.x.y version every month or something.

By the way, I pushed these two changes into the 1.1 release so they are live currently.

**Comment by jhol** [comment]
@AzothAmmo that would work for us. Perhaps it would make sense to respond to all the pull requests and then make a v1.1.1 release.
