### ISSUE TITLE
Is there any posibilities that cereal will support  raw pointers ?

### ISSUE THREAD

**Issue by l3b2w1** [USCiLab/cereal#186]

**Comment by randvoorhies** [comment]
There is no possiblity of this. See the section "**Pointer serialization rationale**" at the bottom of [this documentation page](http://uscilab.github.io/cereal/pointers.html) for an explanation.

**Comment by erichkeane** [comment]
You should consider using in your application if at all possible, which then is quite possible to serialize.  If you REALLY need to have a raw pointer, you can very easily dereference the value and serialize THAT instead of the pointer.  It is a touch more work in your serialize function, but shouldn't be difficult.
