### ISSUE TITLE
Add CBOR support.

### ISSUE THREAD

**Issue by Type1J** [USCiLab/cereal#206]
MessagePack requires knowing lengths before writing, which makes it difficult to implement unless a few hints were sprinkled into each serialization function about how many elements it has.

CBOR does not require that one knows how many elements are going to be in an object (a key value pair, or "map" assuming that you want to use names instead of order for version difference management), and instead has a terminator header byte after the last element. I believe  that this feature of the CBOR format makes it easier than MessagePack (or other formats that require length to be known) to integrate into Cereal, which streams values into its archives, and can't easily seek back to add a length.

**Comment by AzothAmmo** [comment]
Looks interesting - would be great if someone was willing to take on this challenge themselves.  Would fit well as a module.  How popular is this format?

**Comment by erichkeane** [comment]
I've been doing a bunch of work with CBOR lately actually.  One of my coworkers just finished writing this library: https://github.com/01org/tinycbor which works fantastically as a C library.  The nice part is that it works in a stream-mechanism for writing, very similar to how cereal works for encodign, so I'm a pretty big fan.
The downside is it requires pre-allocation of a buffer, which is tough, since you cannot know the buffer size in advance.  It makes it much more efficient (since you just have a buffer, and it writes to it!), but makes it tough to know the size in advance.

Did Cereal Modules make it yet?  I might be able to take a look at one and get a CBOR module started.
