### ISSUE TITLE
how to "forward" serialization to another type

### ISSUE THREAD

**Issue by Trass3r** [USCiLab/cereal#232]
Playing around with QString json serialization (I want utf16 -> utf8).
First I followed the types/string.hpp example which was quite misleading as that is not generic as expected. The text based archives "silently" handle strings differently.

The only thing that really worked so far is:
```cpp
void save(cereal::JSONOutputArchive& ar, const QString& str)
{
	std::string d = str.toUtf8().toStdString();
	ar(CEREAL_NVP(d));
}
```

But it results in a superfluous object as it implies prologue and epilogue being called:
```json
{
    "stdstring": "asdasd",
    "qstring": {
        "d": "sda"
    }
}
```

Also tried json's specific saveValue method:
```cpp
	QByteArray utf8 = str.toUtf8();
	ar.saveValue(utf8.constData());
```

But this crashes as it tries to access 'utf8' in the epilogue afterwards when the object is already destroyed.

**Comment by AzothAmmo** [comment]
The `saveValue` functions are for "internal use only" meaning we don't want you to call them directly in your serialization code since, as you discovered, they require certain complementary function calls normally handled in something like a prologue/epilogue call.  If you were interested in using them you'd have to look at some of the example usage in json.hpp.

I think what you are looking for is a minimal serialization function - take a look at [this page](http://uscilab.github.io/cereal/serialization_functions.html#minimal).

Also note that all serialization functions, even minimal ones, call prologue and epilogue functions. These functions may have different behaviors depending on what is being serialized and do not imply the creation of an object/array in the output JSON.

Regarding the string support in types/string.hpp, we have to design all of these with any possible archive type in mind.  Since we can't know how an archive should process a string, we compromise by providing an implementation only for archives that are designed to optimize loading and saving chunks of binary data.

**Comment by Trass3r** [comment]
Thanks!
The minimal serialization functions look promising for the string case.
I tested saveValue as it was the only way I could find to get a const char* in to avoid another copy of the data. no string_view yet unfortunately :)

Ah ok so BinaryData is more about optimized load/store and not just supported.
(as there is the saveBinaryValue method in the jsonarchive after all)
