### ISSUE TITLE
Deserialize manually created json file

### ISSUE THREAD

**Issue by kaplad** [USCiLab/cereal#245]
Is it possible to deserialise json file with polymorphic objects? For example i have my objects serialized and it looks OK:
```json
{
    "FieldInfo": {
        "Field": {
            "Objects": [
                {
                    "key": "hello",
                    "value": {
                        "polymorphic_id": 2147483649,
                        "polymorphic_name": "ObjectChild",
                        "ptr_wrapper": {
                            "id": 2147483649,
                            "data": {
                                "x": 16807,
                                "y": 16807,
                                "z": 1622650073
                            }
                        }
                    }
                },
                {
                    "key": "hello2",
                    "value": {
                        "polymorphic_id": 1,
                        "ptr_wrapper": {
                            "id": 2147483650,
                            "data": {
                                "x": 984943658,
                                "y": 984943658,
                                "z": 470211272
                            }
                        }
                    }
                }
            ]
        }
    }
}
```

But what if i need to add some new objects here manually (for example with another program) and import them with cereal?

**Comment by AzothAmmo** [comment]
You need to take special care generating the pointer and polymorphic id, since cereal uses those to figure out if it needs to actually allocate a object when loading. Take a look at how they are used in `cereal.hpp`, particularly the `getSharedPointer`, `registerSharedPointer`, `getPolymorphicName`, and `registerPolymorphicName` functions.

Ids are essentially sequential except that we do some bit masking to determine if they are responsible for storing the data or performing a registration. So if you do this outside of cereal, make sure to replicate the bit masking otherwise things will get messy. This isn't officially supported but should work if you properly create the data.
