### ISSUE TITLE
Feature Request: Be able to call shared_from_this after an object has been constructed in load_and_construct

### ISSUE THREAD

**Issue by M2tM** [USCiLab/cereal#283]
It would be hugely beneficial for quite a few of my systems to be able to call shared_from_this after construct().  In many of my things when I create them I utilize shared_ptr in interfaces and being able to pass a shared_ptr after construction is part of my factory methods that make these objects in the first place.  In this regard, being able to do the same work my factory methods are doing in the deserialization process would be super streamlined.

Is there a technical reason that makes it impossible for shared_from_this to return a valid shared_ptr?

Or, atlernatively, is there a way you could expose the shared_ptr that's currently being populated via the cereal::construct object?  IE: Could I call construct.shared_ptr() or construct.shared_from_this() to get the shared_ptr.

```
#include <stringstream>
#include <iostream>
#include "cereal/cereal.hpp"

struct SharedFromThisPlease : public std::enable_shared_from_this<SharedFromThisPlease> {
	virtual ~SharedFromThisPlease(){}

	template <class Archive>
	void serialize(Archive & archive) {}

	template <class Archive>
	static void load_and_construct(Archive & archive, cereal::construct<SharedFromThisPlease> &construct) {
		construct();
		auto selfReference = construct->shared_from_this(); //Breaks here currently
	}
};

#include "cereal/archives/json.hpp"

int main(){
	std::stringstream stream;

	{
		cereal::JSONOutputArchive archive(stream);
		archive(std::make_shared<SharedFromThisPlease>());
	}

	std::shared_ptr<SharedFromThisPlease> loadedResult;
	{
		cereal::JSONInputArchive archive(stream);
		archive(loadedResult);
	}
}
```

**Comment by AzothAmmo** [comment]
I think we can resolve this. 

If you are curious, the error occurs because when we hand things off to you to do your construction and initialization, this is all happening on a buffer of memory so as not to mess up the underlying `weak_ptr` that powers `shared_from_this` (when you do construction, it would overwrite the true `weak_ptr`). This also means that if you call `shared_from_this`, you are going to run into problems. When you exit the `load_and_construct` call, which happens on line 157 in memory.hpp, the destructor for the `EnableSharedStateHelper` restores the `weak_ptr` and you can call `shared_from_this` in peace.

So to fix it we just need to make sure that the `weak_ptr` is restored as soon as you call `construct()`, instead of after you exit `load_and_construct`, which will take some code shuffling to get working.

**Comment by M2tM** [comment]
I'm really excited about this, I was using a goofy "initialized" bool in some places and doing an initialization conditional on that bool in an update method for some of my components.  This wasn't ideal and having this enhancement will be awesome for cleaning that up.

**Comment by M2tM** [comment]
Rad, I had just implemented this, but not in as good a way as you did.  I'm giving this a try!  Thanks dude! :dancers:
