### ISSUE TITLE
std::vector<POD> does not deserialize correctly with PortableBinaryArchive

### ISSUE THREAD

**Issue by nwhitehorn** [USCiLab/cereal#298]
The std::vector<> serializer for arithmetic types using PortableBinaryArchive reads its data using ar( binary_data( vector.data(), static_cast<std::size_t>( vectorSize ) * sizeof(T) ) ). This fails when loading an archive with reversed endianness since the binary loader bypasses the archive endian conversion logic, resulting in all the vector elements having swapped endianness.

Boost's version of this has an "array" serialization method that lets this work. Something like array_data<T>(vector.data(), static_cast<std::size_t>( vectorSize )) would solve the problem here.

**Comment by AzothAmmo** [comment]
The problem here wasn't that we were skipping the endian conversion, but rather that the endian conversion code had some pretty great bugs:

* Output was only swapping the first element in a BinaryData chunk
* Input was swapping the first element repeatedly instead of advancing to subsequent chunks

I added a test case to cover this.

**Comment by nwhitehorn** [comment]
Thanks! That fixed my test case. One other portability note that I noticed but have not encountered: portable_binary.hpp uses bool, which is four bytes on PPC MacOS X.

**Comment by AzothAmmo** [comment]
I'll change that to a `uint8_t` to be safe. Please note this is potentially a breaking change for data saved with the old archive.
