### ISSUE TITLE
json serialization does not have closing brace

### ISSUE THREAD

**Issue by keedongpark** [USCiLab/cereal#299]
It seems a obvious bug, but I cannot find any issue (open / closed). 
Tested with head revision.

**Comment by reuk** [comment]
I've been using the json serializer recently and haven't seen this problem.

Can you post the smallest code sample which exhibits the problem?

**Comment by erichkeane** [comment]
I'm guessing that OP is looking at the output archive before it has been destructed.

OP: You need to make sure that the Output Archive's destructor is called, as it doesn't finalize the JSON package until that happens.  The most common way to do so is (note, not compiled, so names might be off, but hopefully you can get the concept):

    some_stream_type stream;
    {
        JsonOutputArchive archive(stream);
        archive(all_the_things);
    }  // Closing brace here inserts the final JSON brace
    // Observe the stream here!

**Comment by AzothAmmo** [comment]
As @erichkeane said this is due to a misunderstanding of when we output the closing brace. The archives should be disposed of when you are finished with them, usually by letting their scope expire. The next release has much more emphasized documentation around this issue, since this comes up about once every few months.
