### ISSUE TITLE
Exception on extra data

### ISSUE THREAD

**Issue by ztdwu** [USCiLab/cereal#323]
Is there an option to make the serializer throw an exception when there are extra data in the JSON input that cannot be mapped to a field in the struct?

For example, the JSON:
```json
{
    "a": 1,
    "b": 2
}
```
The struct:
```c++
struct Object {
    int a;
};
```
In this case, when serializing the JSON to an Object instance, I would like the serialization process to throw an exception indicating that it has encountered an extra data value `"b"` which cannot be mapped to a member in the Object class.

**Comment by AzothAmmo** [comment]
You can modify the json archive to achieve this. The `JSONInputArchive` uses a stack of `JSONInputArchive::Iterator` objects to manipulate the data it reads using rapidjson. When cereal is done with an object, an epilogue function calls `JSONInputArchive::finishNode()`, which pops the top of the iterator stack. 

You could insert logic here for the iterator stack to check if there were any other remaining things to be read, and throw an exception if this were the case. You could make the logic here as complicated as you wanted, potentially doing some bookkeeping to track every NVP read and then throwing an exception if any one of them was not mapped into your C++ object.

The reason you may need extra logic like that is because cereal lets you read JSON/XML out of order, so long as you know the name of the NVP. Reading out of order adjusts the position of the iterator, so if you used simple logic to see if you were at the end, you may mistakenly believe you haven't mapped everything.

**Comment by ztdwu** [comment]
Thanks, I'll look into it.
