### ISSUE TITLE
Custom shared pointer.

### ISSUE THREAD

**Issue by dtmoodie** [USCiLab/cereal#330]
Hello,

I'd like cereal to interface with the rest of my object factory system, the first hurdle required is to be able to use my custom shared_ptr class instead of std::shared_ptr.  Does anyone have some tips on what I would need to do to do this?

**Comment by nabijaczleweli** [comment]
don't

**Comment by AzothAmmo** [comment]
If you don't need to support polymorphism you can get away with essentially copying the serialization code for `std::shared_ptr` and modifying it to use your type instead. You'll likely also have to add functions to the archives (in `cereal.hpp`) for registering and looking up your previously serialized shared pointers. These functions are so that we don't double save or double load anything.

You won't need to worry about the `PtrWrapper` that we use if you aren't dealing with polymorphism. Additionally if you know that your type won't be used on things lacking default constructors, you can get away with the simplest serialization functions for `shared_ptr` in `types/memory.hpp`

This all changes if you want to support polymorphism, in which case you need to become very familiar with how we currently support it (read through `types/memory.hpp`, `types/polymorphic.hpp`, and `details/polymorphic_impl.hpp`). Try to understand 1) how cereal registers and stores metadata for polymorphic pointers, and 2) the process for serializing a registered polymorphic pointer.
