### ISSUE TITLE
Polymorphic class registration and ID

### ISSUE THREAD

**Issue by ncamino** [USCiLab/cereal#352]
I have a need to serialize polymorphic classes using the name and not the id as the match on serialize in. I've tried using the macros to register the name but that just changes the name associated with the id. Is there a mechanism to get Cereal to just use the name or allow me to specify the polymorphic_id on the serialization out.

**Comment by AzothAmmo** [comment]
cereal uses `polymorphic_id` to hold two bits of metadata, which are used to indicate whether the pointer was null, whether this is the first instance of this particular polymorphic type, and whether we can skip performing polymorphic serialization. 

Internally cereal creates a map from that id to the stored name and then uses the name for all of the polymorphic machinery. 

The other main purpose of serializing the id is that it prevents us from having to save any other metadata associated with the polymorphic type after we've done it once (or loaded it once). We can just use the number instead, which takes up less space and uses less computation.

So to get to your question: with a decent amount of work, you could modify cereal to use the name every time instead of an id, at the cost of additional time and space for serialization. You would need to look at the code every time there is a reference to `registerPolymorphicName` and `registerPolymorphicType`, at the minimum. cereal can't do what you are asking without modification.
