### ISSUE TITLE
Skip an object?

### ISSUE THREAD

**Issue by vspinu** [USCiLab/cereal#372]
This is probably a basic question but I cannot find any references on this. 

If I have 2 objects in a stream, how do I skip the first one without explicitly loading it into a new instance? 

Thanks.

**Comment by AzothAmmo** [comment]
There is currently no official support for this if you are using a binary stream. In JSON or XML, you can specify the name of the NVP to skip over loading something (in the docs this is called out of order loading).

For binary serialization, there are some cases of serialization where the binary size could be accurately computed and used to advance the stream pointer without actually doing a load. However, there are many objects that cereal serializes that cannot be skipped because of optimizations made during saving. For example, cereal only serializes each referenced pointer once, and further serializations of that pointer refer to the previously saved/loaded value. Similar things happen for other unavoidable bits of metadata associated with polymorphism, for example.

So in general, because of the way cereal was designed (minimizing binary size), it is not easily possible to skip over data in a binary stream.

**Comment by vspinu** [comment]
I see. Thank you for the explanation. My use case involves nested lists of heterogenuous C++ primitive vectors only and occasional binary data of which I know the size. If I am not mistaken cereal stores vectors in a [long_length][data] format. So skipping those would be pretty easy if I can get hold of the underlying stream, but `itsStream` is currently private. Any special reason why it's private?

**Comment by M2tM** [comment]
One way to skip elements in a container is to filter them in the save method and serialized a local copy of the vector with only the elements you want.

**Comment by AzothAmmo** [comment]
`itsStream` is private because interacting with it directly could easily break things for most users. You do have access though, because you pass the very same stream to the constructor of the archive.

You are correct on the binary format for vectors, but I would double check with a hex editor to make sure it matches what you expect. If your data is a POD type, cereal directly writes the raw bytes out. Otherwise, a serialization function is called on each element, which can have different behavior.

**Comment by vspinu** [comment]
Yeh, this functionality is non-trivial in a general case. In my case of nested heterogenuous lists I would need to compute the byte size of every sub-list/element before the write in order to be able to skip it on read. Too much work for little gain. So I am abandoning this feature for my application. Thank you for all the responses.
