### ISSUE TITLE
Uninitialized variable in cereal/include/cereal/types/vector.hpp causes new to throw std::bad_alloc.

### ISSUE THREAD

**Issue by mehoggan** [USCiLab/cereal#377]
On lines 54 and 78 at git revision 28f9841 there are two variables of type size_type (aka uint64_t) that are uninitialized. These variables are used to resize vectors passed into the  functions by client code. This should be okay behavior since they are cast to size_t.

However, when compiling on OsX using

Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

The variables get set to 33316061322250 which causes a std::bad_alloc to be thrown on lines 57 and 81 respectively. The error displayed in the terminal as.

openMVG_main_MergeMatches(18450,0x7fff7a0ca000) malloc: *** mach_vm_map(size=266528490582016) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc

Since the size of allocation of the vector is not controlled by client code I do not see how I can fix this code without a patch to libcereal. Shouldn't size be initialized to a default value safe across multiple compilers?

**Comment by erichkeane** [comment]
The line below each (ar (make_size_tag))is supposed to load the length of each from the serialized data. I would expect that those lines are misbehaving in some way. Initializing size in each case would likely do nothing in this case. On Jan 21, 2017 2:41 PM, Matthew Hoggan <notifications@github.com> wrote:On lines 54 and 78 at git revision 28f9841 there are two variables of type size_type (aka uint64_t) that are uninitialized. These variables are used to resize vectors passed into the  functions by client code. This should be okay behavior since they are cast to size_t.
However, when compiling on OsX using
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
The variables get set to 33316061322250 which causes a std::bad_alloc to be thrown on lines 57 and 81 respectively. The error displayed in the terminal as.
openMVG_main_MergeMatches(18450,0x7fff7a0ca000) malloc: *** mach_vm_map(size=266528490582016) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
Since the size of allocation of the vector is not controlled by client code I do not see how I can fix this code without a patch to libcereal. Shouldn't size be initialized to a default value safe across multiple compilers?

**Comment by AzothAmmo** [comment]
As mentioned, those variables are immediately loaded into by the following lines, which will overwrite any value they have.

Are you able to post a reproduction of what is causing your problem? I have a feeling that something is changing your serialized data or loading something in the wrong order, causing a junk value to be loaded.

**Comment by mehoggan** [comment]
After a closer inspection of the code I see what you are saying. This code is being called by OpenMVG in the following manner:

    std::ifstream stream (filename.c_str(), std::ios::in | std::ios::binary);
    if (stream.is_open())
    {
      cereal::PortableBinaryInputArchive archive(stream);
      archive(matches);
      stream.close();
      return true;
    }

The file is a binary match file written by OpenMVG which is contained in the stream variable.

InputArchive::operator(Types && ...args) is called with a single argument of type std::map<std::pair, std::vector>. From there after serveral iterations inside cereal I get the std::bad_alloc and the size variable mentioned above in  CEREAL_LOAD_FUNCTION_NAME is set to the mentioned value above. Does this mean that something in the file written in OpenMVG is corrupt? What should I be looking for. There is only one function call in the call stack to OpenMVG, the rest of my call stack is 99% in the cereal library. I will try and come up with a small reproducible case.

**Comment by mehoggan** [comment]
I have a small reproducible case which can be found at https://github.com/mehoggan/cereal_bug. It removes all of OpenMVG minus the binary file that was produced by OpenMVG. What is it about the file that causes the std::bad_alloc in cereal?

**Comment by nguyenngodinh** [comment]
@mehoggan I have same error. Can you tell me the solution for this problem, please!
