### ISSUE TITLE
std::string serialization on gcc 4.9

### ISSUE THREAD

**Issue by wisealex2** [USCiLab/cereal#380]
as far i see gcc 4.9 uses copy on write optimization. it means there is a shared string value between several instances.
cereal uses const_cast<CharT *>( str.data() ) for writing the value into string
it means it might overwrite an existing shared value of all the string instances
e.g. reading:

std::stringstream ss;
// fillup ss;
cereal::BinaryInputArchive arch(ss);
serialize(arch);
std::string str;
std::vector<std::string> vec(5);
for (int i = 0 ; i < 5; ++i)
{
  arch & str; 
  vec[i] = str;
}

it easy to fix client code - just to construct string in the loop.
possible fix - usage of &str.front() instead of str.data()
 
Thanks for the library

---
gcc (Ubuntu 4.9.4-2ubuntu1~14.04.1) 4.9.4
sorry if it is a duplicate

**Comment by AzothAmmo** [comment]
While I agree that there is the potential for undesired behavior due to the CoW implementation for string, I'm having trouble thinking of a situation where someone using cereal properly would be affected by this.

Your example, for instance, is overly contrived as a user would actually serialize the vector directly, which would avoid the issue. Serializing multiple strings also avoids the issue as they are unique objects.

We could just change it anyway, but we would effectively be introducing an additional construction/copy to each string load.

**Comment by stayprivates** [comment]
Hello,

Just got bitten by this, hard.  Reading previous post, a comment got me worried "I'm having trouble thinking of a situation where someone using cereal **properly** would be affected by this".

class App
{
  BigAndCompilated obj;
  
void receiveFromSocket(BigAndCompilated &);
}

receiveFromSocket is typically invoked on App:obj each time data is received on a sock.  So any code that makes a copy of a string in obj, will possible get its string changed.  What is improper about this usage.

The bug was nasty to find because it would only show up if the new string is of the same size as the original, as a call to resize() with a different value would unshared the string.

**Comment by stayprivates** [comment]
There you go sir,  This builds and run for me.
```

#include <string>
#include <cereal/archives/binary.hpp>
#include <cereal/types/string.hpp>

struct App
{
  // in real application, object is a struct , with strings, and vector of struct that themselves contains string
  // but no need for that to demontrate issue.  In this sample the object is so small that a temporary
  // might be used instead when unserializing, but we've elected to reuse the same object because
  // it saves a lot of memory allocation.
  std::string object;

  std::string waitForDataOnSocket( const std::string &str);
  void unserializedData(const std::string &str);
};

// mock to build serialized data from input instead of real data from socket.
std::string App::waitForDataOnSocket( const std::string &input)
{
  std::ostringstream stream;
  {
    cereal::BinaryOutputArchive oa( stream );
    oa << input;
  }
  return stream.str();
}

void App::unserializedData(const std::string &serializedData)
{
  std::stringstream inputStream;
  {
    inputStream.write(serializedData.data(), serializedData.size() );
    cereal::BinaryInputArchive ia( inputStream );
    ia >> object;
  }
}

int main()
{
  App app;

  // This is pseudo code of our app. Bellow are 4 independ steps, reprensenting sequence of 4 messages
  // for(;notDone;)
  // {
  //     std::string serializedData = app.waitForDataOnSocket("123456789");
  //    app.unserializedData(serializedData);
  //    app.doStuff();
  // }

  {  // Step 1
    std::string serializedData = app.waitForDataOnSocket("123456789");
    app.unserializedData(serializedData);
    std::cout << "\nafter first reception:\n"
                 " app.name = " << app.object << " expect 123456789\n\n";
  }

  // COPY, which is what app.doStuff() does in real app
  std::string copyName(app.object);
  std::cout << "Made copy of app.name in copyName:\n"
               " copyName = " << copyName << " expect 123456789\n\n";

  { // Step 2, receive string of same length
    std::string serializedData = app.waitForDataOnSocket("987654321");
    app.unserializedData(serializedData);

    std::cout << "after new string with same length:\n"
                 " app.name = " << app.object << " expect 987654321\n"
                 " copyName = " << copyName << " expect 123456789\n\n";
  }

  { // Step 3, receive string of same length
    std::string serializedData = app.waitForDataOnSocket("abcdefghi");
    app.unserializedData(serializedData);

    std::cout << "after second new string with same length:\n"
                 " app.name = " << app.object << " expect abcdefghi\n"
                 " copyName = " << copyName << " expect 123456789\n\n";
  }

  { // Step 4, receive string of different length
    std::string serializedData = app.waitForDataOnSocket("abcdefghijklminopqrstuvw");
    app.unserializedData(serializedData);

    std::cout << "after new string with differerent length:\n"
                 " app.name = " << app.object << " expect abcdefghijklminopqrstuvw\n"
                 " copyName = " << copyName << " expect 123456789\n"
                 " here copyName is the same as app.name of previous run because the longer string forced\n"
                 " a resize,  unsharing the string\n"
                 "\n";
  }

  return 0;
}
```
