### ISSUE TITLE
separate *OutputArchive and *InputArchive headers

### ISSUE THREAD

**Issue by headupinclouds** [USCiLab/cereal#406]
Would it be possible to split the archive header files in `cereal/archives/*.hpp` into separate `Input` and `Output` implementations?  When using an explicit archive template instantiation, the current archive files (which include both Input and Ouptut archives) forces instantiation of both types.  Perhaps explicit `Input` and `Output` headers can be added and the current archive headers can include both by default.  That would at least provide users some flexibility.  I expect I can put a PR together for this if it seems appropriate.

This relates to issues in #364.  My sense is splitting the headers is easier than reworking the archive instantiation.  I need to create a small test for this.

The issue stems from the explicit `CEREAL_REGISTER_ARCHIVE` calls for both Input and Output archives at the bottom of each top level archive header:

```
CEREAL_REGISTER_ARCHIVE(cereal::PortableBinaryOutputArchive)
CEREAL_REGISTER_ARCHIVE(cereal::PortableBinaryInputArchive)
```

Update:

I took a quick look at `portable_binary.hpp`.  There is some shared code in the `cereal::portable_binary_detail` namespace that would be moved to a common file, say `cereal/archives/portable_binary_detail.hpp`.  We. would have something like this:

```
cereal/archives/portable_binary_detail.hpp
cereal/archives/portable_binary_input.hpp
cereal/archives/portable_binary_output.hpp
cereal/archives/portable_binary.hpp
```

Also, use of `CEREAL_ARCHIVE_RESTRICT` from `cereal/details/traits.hpp` currently requires both Input and Output types to be visible:
```
#define CEREAL_ARCHIVE_RESTRICT(INTYPE, OUTTYPE) ...
```

We could add 

```
#define CEREAL_ARCHIVE_RESTRICT_INPUT(INTYPE)
#define CEREAL_ARCHIVE_RESTRICT_OUTPUT(INTYPE).
```

Please let me know your thoughts.  Thanks!

**Comment by AzothAmmo** [comment]
I see this issue as a balance between two different goals: one is a (potential) reduction in generated code size, the other is readability and maintainability.

I like that everything there is to know about an archive is maintained in the same header and that from a user's POV, there is only one header to worry about. There's no confusion of whether to include `binary.hpp` or `binary_input.hpp` or `binary_whatever.hpp`. Additionally the implementation for some things can be written in a way that simultaneously addresses input and output (e.g. the cases where we currently use `CEREAL_ARCHIVE_RESTRICT`).

There is also the issue of another macro, `CEREAL_SETUP_ARCHIVE_TRAITS`, which is required for minimal type serialization. cereal needs to know how to go from input to output archive so that it can enforce certain restrictions on serialization functions at compile time. There may be some issues if only an input or output archive is present and these types of serialization functions are used.

That being said an elegant solution to these issues would always be considered.

**Comment by headupinclouds** [comment]
Okay.  Thanks for the detailed background and consideration.  In practice, I would expect any unused archives would be stripped from a final executable or shared library anyway, so the main overhead would be extra compilation time (a reasonable tradeoff).  This lib has worked very well for me.  Thanks!
