### ISSUE TITLE
XML and std::vector<char>

### ISSUE THREAD

**Issue by h-2** [USCiLab/cereal#435]
Luckily XML has real char types in contrast to JSON ( #310). However std::vector<char> is serialised to
```xml
        <value1 size="dynamic">
                <value0>A</value0>
                <value1>C</value1>
                <value2>A</value2>
                <value3>C</value3>
                <value4>A</value4>
                <value5>C</value5>
                <value6>A</value6>
                <value7>C</value7>
                <value8>A</value8>
                <value9>C</value9>
                <value10>A</value10>
                <value11>A</value11>
                <value12>T</value12>
                <value13>T</value13>
                <value14>A</value14>
                <value15>T</value15>
        </value1>
```
while std::string is serialised to:
```
<value2>ACACACACACAATTAT</value2>
```
Obviously the second is much more space efficient and also easier to read. Could you change for the standard containers+char to serialise like string in XML?

Thanks!

PS: I don't know if this change could be made without breaking compatibility 😰

**Comment by AzothAmmo** [comment]
This is something you can implement on your own very easily by overloading the default serialization for `vector` and specializing it for `char`. I imagine this will be slower to serialize or deserialize due to the string construction, but the basic outline is:

```cpp
template <class A> inline
void CEREAL_SAVE_FUNCTION_NAME( cereal::XMLOutputArchive & ar, std::vector<char, A> const & vector );

template <class A> inline
void CEREAL_LOAD_FUNCTION_NAME( cereal::XMLInputArchive & ar, std::vector<char, A> & vector );
```

Converting to string appropriately in those functions. You'll likely also want to specialize `prologue` and `epilogue` not to create a node in the XML for the `vector<char>` serialization function, otherwise you'll end up with output that looks like:

```xml
<value1>
  <value0>ACDADFDASDFDASF</value0>
</value1>
```

Instead of just the inner term.

**Comment by erichkeane** [comment]
>  I imagine this will be slower to serialize or deserialize due to the string construction

I suspect that this would even out in the wash actually, since the construction/output of all the tags seems like it would be a bunch more work.

That said, MY  implementation would use 'string_view' instead if possible (or a cereal::string_view if not), since std::vector<char>::data() is compatible with a string_view.

Pulling it out would likely be able to use the string in place to load it to the vector.

**Comment by h-2** [comment]
Thanks for your comments. Yeah, I thought about doing something along the lines, but copying is not ideal.

> That said, MY implementation would use 'string_view' instead if possible 

string_view serialises to actual data? But its a non-owning data structure!?

**Comment by erichkeane** [comment]
You'd have to write a serializer function most likely (and perhaps teach rapid XML about string view), but there's no reason a non-owning string-view couldn't be copied from into the xml structure.

**Comment by h-2** [comment]
> You'd have to write a serializer function most likely (and perhaps teach rapid XML about string view), but there's no reason a non-owning string-view couldn't be copied from into the xml structure.

Sure it *could* be done, I was only questioning whether something like that *should* be done 😄 

Anyway, we are getting off-topic.
