### ISSUE TITLE
Cereal don't like numbers higher than 8

### ISSUE THREAD

**Issue by Hi-Angel** [USCiLab/cereal#457]
This is an absolutely mystic bug, I spent around 12 hours to find this problem.

If `uint16_t` value is higher than 8 *(tested at least with 9 and 10)*, then instead of 2 bytes it is stored as a single one! Here, look:

```c++
#include <cstdint>
#include <vector>
#include <iterator>
#include <cereal/archives/binary.hpp>

struct tlv_packet_data {
    uint16_t block_sz;

    template<class Archive>
    void save(Archive& archive) const {
        archive(block_sz);
    }
};

template<typename T>
const std::vector<char> serialize(const T& t) {
    std::stringstream ss(std::ios::binary | std::ios::out | std::ios::in);
    cereal::BinaryOutputArchive class_to_ss = {ss};
    class_to_ss(t);
    return { std::istream_iterator<char>(ss),
             std::istream_iterator<char>() };
}

int main() {
    tlv_packet_data auth = tlv_packet_data{9};
    printf("size of the struct is %lu\n", sizeof(tlv_packet_data));
    printf("using 9, serialized size: %lu\n", serialize(auth).size());
    auth.block_sz = 8;
    printf("using 8, serialized size: %lu\n", serialize(auth).size());
}
```

```
$ g++ test.cpp -o a                                               
$ ./a
size of the struct is 2
using 9, serialized size: 1
using 8, serialized size: 2
```

Compiler: g++ version 7.2.1 20171128

**Comment by erichkeane** [comment]
Not a problem with Cereal, it is a problem with your test.  See: http://en.cppreference.com/w/cpp/iterator/istream_iterator

    When reading characters, std::istream_iterator skips whitespace by default (unless disabled with std::noskipws or equivalent), ...

Also note that the values that it skips are 9, 10, 11 ,12 ,13, 32.  Which are Tab, Line Feed, Vertical Tab, Form Feed, Carriage Return, and "Space".

**Comment by AzothAmmo** [comment]
@erichkeane responded right as I was typing my response with your answer. 

Also consider that `stringstream`, even in binary mode, is allowed to append an arbitrary number of null terminators to the end of a stream (see http://en.cppreference.com/w/cpp/io/c#Binary_and_text_modes). Potentially this can result in the size indeed being a byte or so larger than expected. For cereal this isn't a problem since we don't read that data anyway. If you print out the decimal values for your vectors, you would see:

(for 9): `0`
(for 8): `8`, `0`

**Comment by Hi-Angel** [comment]
Jesus Christ… I took that code to convert stream to a vector from StackOverflow by the way. Is there a documented way to get result from Cereal to a vector, or array, or anything I can send over a network?

**Comment by erichkeane** [comment]
There are plenty of ways... though, in your example you could have just as easily done ss.str().data() to get a char array.

**Comment by Hi-Angel** [comment]
Thank you, I confirm, the following function works for me:

```c++
template<typename T>
const std::vector<char> serialize(const T& t) {
    std::stringstream ss(std::ios::binary | std::ios::out | std::ios::in);
    cereal::BinaryOutputArchive class_to_ss = {ss};
    class_to_ss(t);
    std::string s = ss.str();
    return { s.begin(), s.end() };
}
```

I find this kind of ironical that when I found way with iterators, I was glad that it have nothing to do with strings, so I can be sure I won't get screwed by some corner cases like null characters. Turns out everything is upside down: I should be using string but not iterators, ugh.

**Comment by Hi-Angel** [comment]
@AzothAmmo what about additional character in stringstream, is it really something that can happen? Can you please elaborate how Cereal is not affected? *(I am confused, if I get bogus data upon serialization, it can't not affect me, unless I'm missing something)*.

**Comment by erichkeane** [comment]
Note that in your example, you're creating an extra copy of the std::string.  You copy the data both in creating 's' AND when creating the return value.  You can do ss.str().begin() and ss.str().end() to avoid this (or make 's' a const ref).

Additionally, realize that stringstream takes a string-ref parameter, so if you create it ahead of time, you can avoid an extra copy being made as well.  You can at any point access the string's iterators or c_str() (though note it'll not be reliable as a c-string since you'll be interspersing null terminators).

If you want to act on arbitrary memory, you can make a custom basic_streambuf implementation and pass it directly to a basic_stream implementation.  This'll allow you to create any backing store you wish.  One such usage is (though boost has one, boost::asio::streambuf) to have it write directly to a memory device, which is entirely possible.

**Comment by AzothAmmo** [comment]
> Can you please elaborate how Cereal is not affected?

cereal knows exactly how much data to read (or write) from a stream so any data that occurs after the end of the data (such as a potentially appended null terminator) is never read.

**Comment by Hi-Angel** [comment]
Thank you all for replies

> Additionally, realize that stringstream takes a string-ref parameter, so if you create it ahead of time, you can avoid an extra copy being made as well. 

Hmm I looked [its constructors](http://en.cppreference.com/w/cpp/io/basic_stringstream/basic_stringstream), the std::string argument is a constant reference, and is used only for stringstream to have it as initial content.

**Comment by erichkeane** [comment]
Ah, right, I misread that...  The rest of my post stands though, iostreams have some pretty need customization points.
