### ISSUE TITLE
std::variant serialization clashes with boost serialization

### ISSUE THREAD

**Issue by fiesh** [USCiLab/cereal#473]
The serialization routines for `std::variant` currently commited to `develop` clash with the `boost_variant` serialization because the same namespace was chosen, see pull request #448

**Comment by AzothAmmo** [comment]
For now I'm just changing the namespaces but a new issue/PR can be opened to try and consolidate the code as discussed in #448.

**Comment by patrikhuber** [comment]
@AzothAmmo I have one comment regarding the variant serialisation, and I think it fits here, instead of opening a new issue.
`types/boost_variant.hpp` uses `int32_t` to serialise the `which` index. `types/variant.hpp` serialises this with `auto` (save) and `decltype(variant.index())` (load). I am not sure that's a good idea in `types/variant.hpp`. According to [cppreference](http://en.cppreference.com/w/cpp/utility/variant/index), the type of `index()` is `std::size_t`. So I think that means it could be a different type on different platforms - or even be different on the same platform for 32/64 bit compilation. That means an archive with an `std::variant` is not portable, which in my opinion I would even consider a bug. Should we not use `std::uint32_t` for this?
Second, I think it would be great if all variant types used the same type for storing the index. This would mean that we can store something with an `std::variant` into an archive on one platform, and then read this archive on a platform like macOS (which does not have `std::variant`) with something like `boost::variant` or `mpark::variant`. This is a highly desired feature (and indeed something I use this for).

What do you think?
I'm happy to prepare a PR if it helps.

**Comment by AzothAmmo** [comment]
@patrikhuber Good catch, we definitely want to be using fixed sizes when possible. If you want to do the PR go ahead!
